config/routes.rb
Rails.application.routes.draw do
  resources :tabs
  devise_for :users
  root 'tabs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tab.rb
class Tab < ApplicationRecord
  belongs_to :user

  validates_presence_of :url

  def title_or_url
    self.title || self.url
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tabs, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tabs = current_user.tabs.all
    @tab = Tab.new
  end

  def create
    @tab = current_user.tabs.new(tab_params)
    if @tab.save
      respond_to do |format|
        format.js
        format.html { redirect_to root_url }
      end
    else
      flash.now[:danger] = "Unable to save tab."
      @tabs = current_user.tabs
      render :index
    end
  end

  def show
    respond_to do |format|
      format.html { redirect_to root_url }
    end
  end

  def destroy
    @tab = current_user.tabs.where(id: params[:id]).first
    @tab.destroy unless @tab.nil?
    respond_to do |format|
      format.js
      format.html { redirect_to root_url }
    end
  end

  private

  def tab_params
    params.require(:tab).permit(:title, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def octicon(name, size: 32)
    raw(Octicons::Octicon.new(name, height: size, width: size).to_svg)
  end
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/views/application/_flash.html.erb
<div class="application-flash">
  <% flash.each do |key, value| %>
    <div class="alert alert-secondary fade show">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/application/_header.html.erb
<header>
  <%= link_to "Save My Tabs", root_url %>
  <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path, method: 'DELETE' %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaveMyTabs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'application/flash' %>
    <%= render 'application/header' %>
    <%= yield %>
  </body>
</html>

app/views/tabs/_new.html.erb
<%= form_for @tab, remote: true, url: { controller: 'tabs', action: 'create' } do |f| %>
  <button id="new-tab-button" class="btn btn-primary btn-block hideable">Save Tab</button>
  <div id="new-tab-form" class="hideable hidden">
    <%= f.text_field :url, placeholder: 'URL', class: "form-control" %>
    <%= f.text_field :title, placeholder: 'Title (Optional)', class: "form-control" %>
    <%= f.submit "Save", class: "btn btn-primary btn-block" %>
    <button id="close-new-tab" class="btn btn-danger btn-block">Close</button>
  </div>
<% end %>

app/views/tabs/_tab.html.erb
<% unless @tab.id.nil? %>
  <li class="list-group-item" id="tab-<%= tab.id %>">
    <%= link_to tab.title_or_url, tab.url, target: "_blank" %>
    <%= link_to tab_path(tab), method: 'DELETE', remote: true do %>
      <%= octicon('x', size: 14) %>
    <% end %>
  </li>
<% end %>

app/views/tabs/create.js.erb
Array.map(
  [ document.querySelector('main#tabs-index ul.list-group') ],
  ul => {
    let parser = new DOMParser();
    let rawEl = "<%= j(render(partial: 'tabs/tab', locals: { tab: @tab })) %>";
    let li = parser.parseFromString(rawEl, "text/html").activeElement;
    ul.appendChild(li);
  }
);

app/views/tabs/destroy.js.erb
Array.map(
  [ document.getElementById('tab-<%= @tab.id %>') ],
  tab => tab.parentNode.removeChild(tab)
);

app/views/tabs/index.html.erb
<main id="tabs-index">
  <%= render 'tabs/new' %>
  <ul class="list-group">
    <%= render @tabs %>
  </ul>
</main>